language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
install:
- npm install
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE freementors;' -U postgres
notifications: 
  email: false
script: 
  - "npm run test"
after_success:
  - "npm run coverage"
sudo: false
